# Traffic Monitoring System Configuration

# Hardware acceleration settings
hardware:
  use_gpu: false  # Master switch for GPU acceleration
  provider: "auto"  # Options: "auto", "cuda", "tensorrt", "openvino", "directml", "rocm"
  precision: "fp32"  # Options: "fp32", "fp16"

# Detection settings
detection:
  confidence: 0.25
  iou_threshold: 0.45
  # Model version settings
  model_versions:
    vehicle_model: "yolo11"  # Options: "yolov5", "yolov8", "yolo11"
    plate_model: "yolov8"    # Options: "yolov5", "yolov8", "yolo11"
  # Vehicle class settings
  vehicle_classes:
    # Standard COCO class IDs for vehicles
    # 0:person, 1:bicycle, 2:car, 3:motorcycle, 5:bus, 7:truck
    enabled_classes: [0, 1, 2, 3, 5, 7]  # Default: all vehicle classes
    class_names:
      0: "person"
      1: "bicycle"
      2: "car"
      3: "motorcycle" 
      5: "bus"
      7: "truck"
    # Count specific classes only (empty means count all enabled classes)
    count_classes: []

# Tracking settings
tracking:
  tracker_type: bytetrack  # Options: bytetrack, botsort, strongsort, ocsort, deepocsort
  confidence: 0.3
  
  # Reid model weights path (used by trackers that support ReID)
  reid_weights: "osnet_x0_25_msmt17.pt"
  
  # Common tracking parameters
  max_age: 30
  min_hits: 3
  frame_rate: 30
  
  # ByteTrack specific parameters
  bytetrack:
    track_thresh: 0.6
    track_buffer: 30
    match_thresh: 0.9
    min_box_area: 10
    
  # BoTSORT specific parameters
  botsort:
    track_high_thresh: 0.6
    track_low_thresh: 0.1
    new_track_thresh: 0.7
    track_buffer: 30
    match_thresh: 0.7
    cmc_method: "sparseOptFlow"
    proximity_thresh: 0.5
    appearance_thresh: 0.25
    with_reid: true
    
  # StrongSORT specific parameters
  strongsort:
    min_conf: 0.6
    ema_alpha: 0.9
    max_dist: 0.2
    max_iou_distance: 0.7
    n_init: 3
    nn_budget: 100
    mc_lambda: 0.995
    
  # OCSort specific parameters
  ocsort:
    det_thresh: 0.6
    max_age: 30
    min_hits: 3
    iou_threshold: 0.3
    delta_t: 3
    asso_func: "iou"
    inertia: 0.2
    use_byte: false
    
  # DeepOCSort specific parameters
  deepocsort:
    det_thresh: 0.5
    max_age: 30
    min_hits: 3
    iou_threshold: 0.3
    delta_t: 3
    asso_func: "iou"
    inertia: 0.2
    w_association_emb: 0.75

# OCR settings
ocr:
  languages: [en]
  use_gpu: false

# Counting settings
counting:
  # Whether to use raw pixel coordinates instead of normalized coordinates
  use_raw_coordinates: true  # Set to true by default for more intuitive setup
  
  # Counting line coordinates
  # IMPORTANT: This should be customized for each video to match the specific road position
  # If use_raw_coordinates is false, values should be between 0-1 (normalized)
  # If use_raw_coordinates is true, values should be pixel coordinates
  raw_coordinates:
    start: [344, 651]
    end: [1912, 673]
  normalized_coordinates:
    start: [0.25, 0.6]
    end: [0.75, 0.6]

# Video processing settings
video:
  frame_skip: 2
  output_fps: 20
  process_resolution: [640, 640]

# MQTT settings
mqtt:
  topic_prefix: traffic_monitoring
